### ISSUE TITLE
Wrong import path in declaration file with typescript 2.9.2 [ts-transform-paths]

### ISSUE THREAD

**Issue by filenwind** [zerkalica/zerollup#4]
Sorry it's me again and really hard to describe the issue with my poor english.

This is sample [repos](https://github.com/filenwind/ts-transform-paths-issue).

```bash
npm run build:ttsc
```

After compile, the User morning and afternoon method in declaration file will appear wrong import path,

even if I use the relative path, you can see files [UserRelative](https://github.com/filenwind/ts-transform-paths-issue/blob/master/src/app/UserRelative.ts) and [UserAlias](https://github.com/filenwind/ts-transform-paths-issue/blob/master/src/app/UserAlias.ts) both have same issue, but no problem with **someType**.

And it's work fine with typescript 2.9.1,  sorry I don't know is ts-transform-paths issue or not.

```bash
yarn upgrade typescript@2.9.1
npm run build:ttsc
```
Really thanks for your help!

User.ts

```js
import factory from 'app/factory';
import { someType } from 'app/factory';

class User {
  public name = 'John';
  public test?: someType;
  public double = (prefix: string) => {
    return {
      name: `${prefix} ${this.name.repeat(2)}`,
    };
  };
  public triple = (prefix: string) => {
    return {
      name: `${prefix} ${this.name.repeat(3)}`,
    };
  };

  public morning = factory('Morning', this.double);
  public afternoon = factory('Afternoon', this.triple);
}

export default User;

```

Factory.ts
```js
import { Data } from 'app/type';

export interface someType {
  someProperty: string;
}

type transform = (prefix: string) => Data;

const factory = (prefix: string, transform: transform) => () => {
  return transform(prefix);
}

export default factory;

```

type.ts
```js
export type Data = {
  name: string;
};

```

**Comment by zerkalica** [comment]
Can you show wrong results (resulting js)?

**Comment by filenwind** [comment]
Oh, sorry

The wrong  result is in declaration file.

[repos](https://github.com/filenwind/ts-transform-paths-issue)
```bash
npm run build:ttsc
```
Both `./dist/app/UserAlias.d.ts` and `./dist/app/UserRelative.d.ts` will has error like below:
```ts
import { someType } from './factory';
declare class User {
    name: string;
    test?: someType;
    double: (prefix: string) => {
        name: string;
    };
    triple: (prefix: string) => {
        name: string;
    };
    morning: () => import("app/type").Data; // Cannot find module 'app/type'.
    afternoon: () => import("app/type").Data; // Cannot find module 'app/type'.
}
export default User;

```

But will work at typescript 2.9.1, is typescript mistake?

**Comment by zerkalica** [comment]
It's a new typescript feature: now imports expands in d.ts files

Fixed, check 1.4.4

**Comment by filenwind** [comment]
Sorry, I tried, looks like issue still exist.

[repos](https://github.com/filenwind/ts-transform-paths-issue)

**Comment by zerkalica** [comment]
small fix, that was not tested, try 1.4.5

**Comment by filenwind** [comment]
Awesome~!  Thank you~!
